version: '2'
services:
  web:
    build: ../repos/labofolio
    image: foway/web
    command: npm start
    volumes:
      - "$PWD/../repos/labofolio/api:/user/app/api"
      - "$PWD/../repos/labofolio/index.js:/user/app/index.js"
      - "$PWD/../repos/labofolio/package.json:/user/package.json"
    ports:
      - 8080:3000