version: '2'
services:
  web1:
    build: ../repos/labofolio
    image: foway/web
    volumes:
      - "$PWD/../repos/labofolio/api:/usr/src/app/api"
      - "$PWD/../repos/labofolio/core:/usr/src/app/core"
      - "$PWD/../repos/labofolio/app.js:/usr/src/app/app.js"
      - "$PWD/../repos/labofolio/package.json:/usr/src/app/package.json"
      - "$PWD/../repos/labofolio/package-lock.json:/usr/src/app/package-lock.json"
    ports:
      - 3001:3000
    hostname: local-web1
    depends_on:
    - local-store
    environment:
    - SERVICE_PORT=3000
    - SERVICE_ENV=local
    - SERVICE_MODE=api

  web2:
    image: foway/web
    ports:
    - 3002:3000
    hostname: local-web2
    depends_on:
    - local-store
    environment:
    - SERVICE_PORT=3000
    - SERVICE_ENV=local
    - SERVICE_MODE=api

  web3:
    image: foway/web
    ports:
    - 3003:3000
    hostname: local-web3
    depends_on:
    - local-store
    environment:
    - SERVICE_PORT=3000
    - SERVICE_ENV=local
    - SERVICE_MODE=api

  local-store:
    build: mysql/master
    volumes:
    - "$PWD/../mysql/mysql_data:/var/lib/mysql"
    mem_limit: 536870912
    image: foway/store
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    hostname: local-store
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_USER=foway
    - MYSQL_PASSWORD=qwerty
    - MYSQL_DATABASE=sample

  local-nginx:
    build: nginx
    image: foway/nginx
    ports:
    - 3000:80
    depends_on:
    - web1
    - web2
    - web3
    links:
    - web1:local-web1
    - web2:local-web2
    - web3:local-web3