#!/usr/bin/env bash

all: help

help: ## ヘルプ表示
	@fgrep -h "##" $(MAKEFILE_LIST) | fgrep -v fgrep | sed -e 's/\\$$//' | sed -e 's/##//'

dressup: ##: docker start
	docker-compose build && docker-compose up