version: "2.4"

services:

  # web api
  local-web-api:
    build: repos/labofolio
    image: foway/web-api
    hostname: local-web-api
    ports:
      - 3000:3000
      - 53000:53000
    mem_limit: 256m
    volumes:
      - "$PWD/repos/labofolio/index.js:/usr/src/app/index.js"
      - "$PWD/repos/labofolio/shared:/usr/src/app/shared"
      - "$PWD/repos/labofolio/core:/usr/src/app/core"
      - "$PWD/repos/labofolio/mode:/usr/src/app/mode"
      - "$PWD/repos/labofolio/tools:/usr/src/app/tools"
      - "$PWD/repos/labofolio/services:/usr/src/app/services"
      - "$PWD/repos/labofolio/middleware:/usr/src/app/middleware"
    env_file:
      - .env
    environment:
      - SERVICE_HOST=local-web-api
      - SERVICE_ENV=local
      - SERVICE_MODE=web-api
      - SERVICE_PORT=3000
    depends_on:
      - local-store

  #########################
  # Proxy Server
  #########################
  local-nginx:
    build: extends/nginx
    image: foway/nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - local-web-api

  #########################
  # DEPENDENCIES DATA STORE
  #########################
  local-store:
    build: extends/mysql
    image: foway/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    hostname: local-store
    ports:
      - 3306:3306
    mem_limit: 512m
    volumes:
      - "$PWD/backup/mysql/mysql_data:/var/lib/mysql"
      - "$PWD/backup/mysql/init/master.d:/docker-entrypoint-initdb.d"
    env_file:
      - mysql.env