version: "3.7"

services:

  # web api
  # TODO : cpu && memory limits
  local-web-api:
    build: repos/labofolio
    image: foway/web-api
    ports:
      - 3000:3000
    depends_on:
      - local-store
    volumes:
      - "$PWD/repos/labofolio/index.js:/usr/src/app/index.js"
      - "$PWD/repos/labofolio/shared:/usr/src/app/shared"
    environment:
      - SERVICE_ENV=local
      - SERVICE_MODE=web-api
      - SERVICE_PORT=3000
      - MYSQL_HOST=local-store
      - MYSQL_PORT=3306

  # TODO replica ???
  local-store:
    build: extends/mysql
    volumes:
      - "$PWD/backup/mysql/mysql_data:/var/lib/mysql"
      - "$PWD/backup/mysql/init/master.d:/docker-entrypoint-initdb.d"
    image: foway/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    hostname: local-store
    ports:
      - 3306:3306
      - 13306:13306
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=foway
      - MYSQL_PASSWORD=qwerty
      - MYSQL_DATABASE=sample