version: "2.0"
services:
  api:
    build: repos/labofolio-api
    image: foway/labofolio-api
    container_name: local-api
    command: npm run dev
    ports:
      - 3000:3000
    mem_limit: 256m
    volumes:
      - "$PWD/repos/labofolio-api/tsconfig.json:/usr/src/app/tsconfig.json"
      - "$PWD/repos/labofolio-api/package.json:/usr/src/app/package.json"
      - "$PWD/repos/labofolio-api/src:/usr/src/app/src"
    networks:
      default:
        aliases:
          - local-api
    depends_on:
      - mysql
      - redis
    env_file:
      - .env.api

  bff:
    build: repos/labofolio-bff
    image: foway/labofolio-bff
    container_name: local-bff
    #command: go run main.go
    ports:
      - 3001:3000
    mem_limit: 256m
    volumes:
      - "$PWD/repos/labofolio-bff/main.go:/usr/src/app/main.go"
    networks:
      default:
        aliases:
          - local-bff
    depends_on:
      - mysql
      - redis

  nginx:
    build: extends/nginx
    image: foway/labofolio-nginx
    container_name: local-nginx
    ports:
      - 443:443
    depends_on:
      - api

  mysql:
    build: extends/mysql
    image: foway/mysql
    container_name: local-mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - 3306:3306
    mem_limit: 512m
    volumes:
      - "$PWD/backup/mysql:/var/lib/mysql"
    networks:
      default:
        aliases:
          - local-mysql
    env_file:
      - .env.mysql

  redis:
    build: extends/redis
    image: foway/redis
    container_name: local-redis
    #command: redis-cluster
    ports:
      - 7000:7000
      - 7001:7001
      - 7002:7002
      - 7003:7003
      - 7004:7004
      - 7005:7005
    networks:
      default:
        aliases:
          - local-redis